services:
  kingshot-redeemer:
    image: brenak/kingshot-redeemer:latest
    container_name: sdw-redeemer-bot
    restart: unless-stopped
    command: python -u main.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TIMEOUT_MS=${TIMEOUT_MS}
    volumes:
      - kingshot-data:/app/data
    networks:
      - bot-network

volumes:
  kingshot-data:
    name: kingshot-data

networks:
  bot-network:
    driver: bridge